### ISSUE TITLE
svpk不能加载吗？

### ISSUE THREAD

**Issue by 7235201** [CJLU-source/Synthesizer-V-FE#1]
如题，谢谢

**Comment by CJLU-source** [comment]
SVPK 只为最新版的 SV 设计，本版是 SVE 的最后一版（Build 018）。所以只能使用之前的 EXE 音源。
SVE 使用了 VM 壳，难度有点大，目前在 Mac 与 Linux 上寻找突破口，但是成功的可能性不大。
